/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['balance', 'createdAt', 'currency', 'id', 'name', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare balance: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'after',
    'before',
    'createdAt',
    'entityId',
    'entityType',
    'id',
    'ipAddress',
    'userAgent',
    'userId',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare after: any | null
  @column()
  declare before: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class InviteCodeSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'updatedAt', 'used', 'usedAt', 'usedBy'] as const
  $columns = InviteCodeSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare used: boolean
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare usedBy: number | null
}

export class TransactionSchema extends BaseModel {
  static $columns = [
    'accountId',
    'amount',
    'createdAt',
    'description',
    'id',
    'type',
    'userId',
  ] as const
  $columns = TransactionSchema.$columns
  @column()
  declare accountId: number | null
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
